"""rag/inject_context.py — Query the RAG corpus and write results to docs/RAG_CONTEXT.md.

Usage:
    python rag/inject_context.py --query "option chain filtering" --top-k 5
    python rag/inject_context.py --query "EMA warm-up" --top-k 3 --output docs/RAG_CONTEXT.md

The output file is read by GitHub Copilot as workspace context during development.
"""

import argparse
import sys
from datetime import date
from pathlib import Path

# Allow running from project root without installing as a package
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from rag.storage.doc_store import DocStore
from rag.storage.bm25_store import BM25Store

_DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "RAG_CONTEXT.md"


def format_results(query: str, results: list[dict]) -> str:
    """Format BM25 results as Markdown for Copilot consumption."""
    lines = [
        "# RAG_CONTEXT — QuantConnect Documentation",
        "",
        f"> **Query:** `{query}`  ",
        f"> **Generated:** {date.today().isoformat()}  ",
        f"> **Chunks returned:** {len(results)}",
        "",
        "---",
        "",
        "> This file is auto-generated by `rag/inject_context.py`.",
        "> Treat these excerpts as authoritative QuantConnect API reference.",
        "> Regenerate before asking questions about specific QC APIs:",
        "> ```bash",
        f'> python rag/inject_context.py --query "{query}" --top-k {len(results)}',
        "> ```",
        "",
        "---",
        "",
    ]

    for i, result in enumerate(results, start=1):
        meta = result.get("metadata", {})
        url = meta.get("url", "unknown")
        section = " › ".join(meta.get("section_path", []))
        score = result.get("score", 0.0)

        lines += [
            f"## Result {i} — {section}",
            "",
            f"**Source:** [{url}]({url})  ",
            f"**BM25 score:** {score:.4f}  ",
            f"**Crawled:** {meta.get('crawl_date', 'unknown')}",
            "",
            result["text"],
            "",
            "---",
            "",
        ]

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Query the QC docs RAG corpus and write top-k results to RAG_CONTEXT.md."
    )
    parser.add_argument(
        "--query",
        required=True,
        help="Search query (plain text or keywords)",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=5,
        metavar="N",
        help="Number of results to return (default: 5)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_DEFAULT_OUTPUT,
        metavar="PATH",
        help=f"Output file path (default: {_DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print results to stdout instead of writing to file",
    )
    args = parser.parse_args()

    # Load stores
    doc_store = DocStore()
    doc_store.load()

    if len(doc_store) == 0:
        print(
            "[inject_context] No documents in store. "
            "Run ingest_pipeline.py first:\n"
            "  python rag/pipelines/ingest_pipeline.py --sections indicators",
            file=sys.stderr,
        )
        sys.exit(1)

    bm25_store = BM25Store()
    bm25_store.load()

    results = bm25_store.search(args.query, doc_store, top_k=args.top_k)

    if not results:
        print(f"[inject_context] No results found for: {args.query}", file=sys.stderr)
        sys.exit(0)

    output = format_results(args.query, results)

    if args.stdout:
        print(output)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output, encoding="utf-8")
        print(f"[inject_context] Wrote {len(results)} results → {args.output}")


if __name__ == "__main__":
    main()
